const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {Pool}=require('pg');
const Busboy=require('busboy');

const PORT=Number(process.env.PORT||10000);
const ROOT=__dirname;
if(!process.env.DATABASE_URL){console.error('DATABASE_URL is required');process.exit(1);}
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='false'?false:{rejectUnauthorized:false},max:Number(process.env.DB_POOL_MAX||5),connectionTimeoutMillis:10000});
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.mp4':'video/mp4','.webm':'video/webm','.svg':'image/svg+xml'};
const json=(res,status,obj)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':process.env.ALLOWED_ORIGIN||'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(obj));};
const text=(res,status,s)=>{res.writeHead(status,{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'});res.end(s);};
function body(req,limit=2e6){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>limit){req.destroy();reject(Error('Request too large'));}});req.on('end',()=>{try{resolve(d?JSON.parse(d):{});}catch{reject(Error('Invalid JSON'));}});req.on('error',reject);});}
async function q(sql,p=[]){return pool.query(sql,p);}
function hash(p,s){return crypto.scryptSync(p,s,64).toString('hex');}
function publicUser(u,extra={}){return {id:u.id,username:u.username,displayName:u.display_name,email:u.email||'',phone:u.phone||'',gender:u.gender||'',dob:u.dob||'',bio:u.bio||'',role:u.role||'user',profileMediaId:u.profile_media_id||null,createdAt:u.created_at,...extra};}
function token(){return crypto.randomBytes(32).toString('hex');}
function clean(s,n=500){return String(s??'').trim().slice(0,n);}
async function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const r=await q(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=$1`,[h.slice(7)]);return r.rows[0]||null;}
async function initDb(){
 await q(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,display_name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,phone TEXT,gender TEXT,dob TEXT,password_salt TEXT NOT NULL,password_hash TEXT NOT NULL,bio TEXT NOT NULL DEFAULT '',role TEXT NOT NULL DEFAULT 'user',profile_media_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_media_id TEXT`);
 await q(`CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS wallets(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,coins BIGINT NOT NULL DEFAULT 0,reserved BIGINT NOT NULL DEFAULT 0)`);
 await q(`CREATE TABLE IF NOT EXISTS media(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,mime TEXT NOT NULL,data BYTEA NOT NULL,size_bytes INT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS posts(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,media_id TEXT REFERENCES media(id) ON DELETE SET NULL,caption TEXT NOT NULL DEFAULT '',visibility TEXT NOT NULL DEFAULT 'public',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS follows(follower_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,following_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(follower_id,following_id),CHECK(follower_id<>following_id))`);
 await q(`CREATE TABLE IF NOT EXISTS likes(user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,post_id TEXT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(user_id,post_id))`);
 await q(`CREATE TABLE IF NOT EXISTS comments(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,post_id TEXT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,text TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,sender_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,recipient_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,text TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),read_at TIMESTAMPTZ)`);
 await q(`CREATE INDEX IF NOT EXISTS messages_pair_idx ON messages(sender_id,recipient_id,created_at)`);
 await q(`CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL,actor_id TEXT,post_id TEXT,message TEXT NOT NULL,read_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS match_actions(user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,target_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,action TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(user_id,target_id))`);
 await q(`CREATE TABLE IF NOT EXISTS matches(id TEXT PRIMARY KEY,user_a TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,user_b TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_a,user_b))`);
 await q(`CREATE TABLE IF NOT EXISTS game_invites(id TEXT PRIMARY KEY,from_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,to_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,game TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS support_tickets(id TEXT PRIMARY KEY,user_id TEXT,issue TEXT NOT NULL,diagnosis TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS ai_events(id TEXT PRIMARY KEY,event TEXT NOT NULL,details JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
}
function staticFile(req,res){
 const u=new URL(req.url,'http://localhost');let p=decodeURIComponent(u.pathname);if(p==='/')p='/index.html';
 const f=path.resolve(ROOT,'.'+p);if(!f.startsWith(ROOT)||!fs.existsSync(f))return json(res,404,{error:'Not found'});
 res.writeHead(200,{'Content-Type':mime[path.extname(f).toLowerCase()]||'application/octet-stream','Cache-Control':'no-cache'});fs.createReadStream(f).pipe(res);
}
function addNotification(userId,type,actorId,message,postId=null){return q(`INSERT INTO notifications(id,user_id,type,actor_id,post_id,message) VALUES($1,$2,$3,$4,$5,$6)`,[crypto.randomUUID(),userId,type,actorId,postId,message]).catch(()=>{});}
function oppositeGender(g){return g==='Male'?'Female':g==='Female'?'Male':null;}
async function parseMultipart(req){
 return new Promise((resolve,reject)=>{
  let bb;try{bb=Busboy({headers:req.headers,limits:{fileSize:60*1024*1024,files:1,fields:20}})}catch(e){return reject(e)}
  const fields={};let file=null;let tooBig=false;
  bb.on('field',(n,v)=>fields[n]=v);
  bb.on('file',(name,stream,info)=>{const chunks=[];let size=0;stream.on('data',c=>{size+=c.length;chunks.push(c)});stream.on('limit',()=>{tooBig=true});stream.on('end',()=>{file={field:name,filename:info.filename,mime:info.mimeType,size,data:Buffer.concat(chunks)}})});
  bb.on('error',reject);bb.on('finish',()=>tooBig?reject(Error('File is too large (60 MB maximum)')):resolve({fields,file}));
  req.pipe(bb);
 });
}
async function main(){
 await initDb();
 const server=http.createServer(async(req,res)=>{
  if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':process.env.ALLOWED_ORIGIN||'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});return res.end();}
  try{
   if(req.url==='/api/health'&&req.method==='GET'){await q('SELECT 1');return json(res,200,{ok:true,service:'Blizz API',database:'postgresql'});}
   if(req.url==='/api/signup'&&req.method==='POST'){
    const b=await body(req),username=clean(b.username,30).toLowerCase().replace(/^@/,'');display=clean(b.displayName||username,60);email=clean(b.email,120).toLowerCase();phone=clean(b.phone,30);gender=clean(b.gender,30);dob=clean(b.dob,30);password=String(b.password||'');
    if(!/^[a-z0-9_.]{3,30}$/.test(username))return json(res,400,{error:'Username must be 3–30 letters, numbers, _ or .'});if(!display||!email||!password||password.length<8||!dob||!gender)return json(res,400,{error:'Username, display name, email, password, DOB and gender are required.'});
    if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json(res,400,{error:'Enter a valid email.'});
    const exists=await q('SELECT 1 FROM users WHERE username=$1 OR email=$2',[username,email]);if(exists.rows[0])return json(res,409,{error:'That username or email is already in use.'});
    const salt=crypto.randomBytes(16).toString('hex'),id=crypto.randomUUID(),u=await q(`INSERT INTO users(id,username,display_name,email,phone,gender,dob,password_salt,password_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[id,username,display,email,phone,gender,dob,salt,hash(password,salt)]);
    await q('INSERT INTO wallets(user_id) VALUES($1)',[id]);const t=token();await q('INSERT INTO sessions(token,user_id) VALUES($1,$2)',[t,id]);return json(res,201,{user:publicUser(u.rows[0]),token:t});
   }
   if(req.url==='/api/login'&&req.method==='POST'){
    const b=await body(req),login=clean(b.login,120).toLowerCase(),password=String(b.password||'');const r=await q(`SELECT * FROM users WHERE lower(username)=$1 OR lower(email)=$1 OR phone=$1`,[login]);const u=r.rows[0];
    if(!u||hash(password,u.password_salt)!==u.password_hash)return json(res,401,{error:'Incorrect username/email or password.'});const t=token();await q('INSERT INTO sessions(token,user_id) VALUES($1,$2)',[t,u.id]);return json(res,200,{user:publicUser(u),token:t});
   }
   if(req.url==='/api/logout'&&req.method==='POST'){const h=req.headers.authorization||'';if(h.startsWith('Bearer '))await q('DELETE FROM sessions WHERE token=$1',[h.slice(7)]);return json(res,200,{ok:true});}
   if(req.url==='/api/me'&&req.method==='GET'){const u=await auth(req);if(!u)return json(res,401,{error:'Not signed in'});return json(res,200,{user:publicUser(u)});}
   if(req.url==='/api/profile'&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Not signed in'});const b=await body(req);const d=clean(b.displayName??u.display_name,60),bio=clean(b.bio??u.bio,160);const r=await q('UPDATE users SET display_name=$1,bio=$2 WHERE id=$3 RETURNING *',[d,bio,u.id]);return json(res,200,{user:publicUser(r.rows[0])});}
   const prof=req.url.match(/^\/api\/users\/([^/?]+)$/);if(prof&&req.method==='GET'){const username=decodeURIComponent(prof[1]).replace(/^@/,'').toLowerCase();const r=await q(`SELECT u.*,COALESCE((SELECT count(*) FROM follows WHERE following_id=u.id),0)::int followers,COALESCE((SELECT count(*) FROM follows WHERE follower_id=u.id),0)::int following,COALESCE((SELECT count(*) FROM posts WHERE user_id=u.id),0)::int posts FROM users u WHERE lower(u.username)=$1`,[username]);if(!r.rows[0])return json(res,404,{error:'User not found'});return json(res,200,{user:publicUser(r.rows[0],{followers:r.rows[0].followers,following:r.rows[0].following,posts:r.rows[0].posts})});}
   if(req.url==='/api/media'&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const {file}=await parseMultipart(req);if(!file||!file.data?.length)return json(res,400,{error:'No media selected'});const id=crypto.randomUUID();await q('INSERT INTO media(id,user_id,mime,data,size_bytes) VALUES($1,$2,$3,$4,$5)',[id,u.id,file.mime,file.data,file.size]);return json(res,201,{mediaId:id,url:`/api/media/${id}`});}
   const media=req.url.match(/^\/api\/media\/([^/?]+)$/);if(media&&req.method==='GET'){const r=await q('SELECT mime,data FROM media WHERE id=$1',[media[1]]);if(!r.rows[0])return text(res,404,'Not found');res.writeHead(200,{'Content-Type':r.rows[0].mime,'Cache-Control':'public,max-age=31536000'});return res.end(r.rows[0].data);}
   if(req.url==='/api/profile/photo'&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const {file}=await parseMultipart(req);if(!file)return json(res,400,{error:'No image selected'});if(!/^image\//.test(file.mime))return json(res,400,{error:'Profile picture must be an image'});const id=crypto.randomUUID();await q('INSERT INTO media(id,user_id,mime,data,size_bytes) VALUES($1,$2,$3,$4,$5)',[id,u.id,file.mime,file.data,file.size]);const r=await q('UPDATE users SET profile_media_id=$1 WHERE id=$2 RETURNING *',[id,u.id]);return json(res,200,{user:publicUser(r.rows[0]),url:`/api/media/${id}`});}
   if(req.url==='/api/posts'&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const {fields,file}=await parseMultipart(req);if(!file)return json(res,400,{error:'Choose a photo or video'});const mid=crypto.randomUUID();await q('INSERT INTO media(id,user_id,mime,data,size_bytes) VALUES($1,$2,$3,$4,$5)',[mid,u.id,file.mime,file.data,file.size]);const id=crypto.randomUUID();const p=await q('INSERT INTO posts(id,user_id,media_id,caption,visibility) VALUES($1,$2,$3,$4,$5) RETURNING *',[id,u.id,mid,clean(fields.caption,1000),clean(fields.visibility||'public',20)]);return json(res,201,{post:p.rows[0],url:`/api/media/${mid}`});}
   if(req.url==='/api/feed'&&req.method==='GET'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const tab=new URL(req.url,'http://x').searchParams.get('tab')||'forYou';let sql=`SELECT p.*,m.mime AS media_mime,u.username,u.display_name,u.profile_media_id,(SELECT count(*) FROM likes l WHERE l.post_id=p.id)::int likes,(SELECT count(*) FROM comments c WHERE c.post_id=p.id)::int comments,EXISTS(SELECT 1 FROM likes l WHERE l.post_id=p.id AND l.user_id=$1) liked FROM posts p JOIN users u ON u.id=p.user_id LEFT JOIN media m ON m.id=p.media_id WHERE p.visibility='public'`;const params=[u.id];if(tab==='following'){sql+=` AND (p.user_id=$1 OR EXISTS(SELECT 1 FROM follows f WHERE f.follower_id=$1 AND f.following_id=p.user_id))`;}else if(tab==='friends'){sql+=` AND (p.user_id=$1 OR EXISTS(SELECT 1 FROM follows a WHERE a.follower_id=$1 AND a.following_id=p.user_id) AND EXISTS(SELECT 1 FROM follows b WHERE b.follower_id=p.user_id AND b.following_id=$1))`;}sql+=' ORDER BY p.created_at DESC LIMIT 30';const r=await q(sql,params);return json(res,200,{posts:r.rows.map(x=>({...x,url:x.media_id?`/api/media/${x.media_id}`:null,username:x.username,displayName:x.display_name,profileMediaId:x.profile_media_id,mime:x.media_mime}))});}
   const follow=req.url.match(/^\/api\/follow\/([^/?]+)$/);if(follow&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const target=(await q('SELECT * FROM users WHERE lower(username)=$1',[decodeURIComponent(follow[1]).replace(/^@/,'').toLowerCase()])).rows[0];if(!target||target.id===u.id)return json(res,400,{error:'Invalid account'});const existing=await q('SELECT 1 FROM follows WHERE follower_id=$1 AND following_id=$2',[u.id,target.id]);if(existing.rows[0]){await q('DELETE FROM follows WHERE follower_id=$1 AND following_id=$2',[u.id,target.id]);return json(res,200,{following:false});}await q('INSERT INTO follows(follower_id,following_id) VALUES($1,$2)',[u.id,target.id]);await addNotification(target.id,'follow',u.id,`@${u.username} followed you`);return json(res,200,{following:true});}
   if(req.url==='/api/like'&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const b=await body(req),p=(await q('SELECT * FROM posts WHERE id=$1',[b.postId])).rows[0];if(!p)return json(res,404,{error:'Post not found'});const ex=await q('SELECT 1 FROM likes WHERE user_id=$1 AND post_id=$2',[u.id,p.id]);if(ex.rows[0]){await q('DELETE FROM likes WHERE user_id=$1 AND post_id=$2',[u.id,p.id]);return json(res,200,{liked:false});}await q('INSERT INTO likes(user_id,post_id) VALUES($1,$2)',[u.id,p.id]);if(p.user_id!==u.id)await addNotification(p.user_id,'like',u.id,`@${u.username} liked your post`,p.id);return json(res,200,{liked:true});}
   if(req.url==='/api/comment'&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const b=await body(req),t=clean(b.text,500);if(!t)return json(res,400,{error:'Comment cannot be empty'});const p=(await q('SELECT * FROM posts WHERE id=$1',[b.postId])).rows[0];if(!p)return json(res,404,{error:'Post not found'});const id=crypto.randomUUID();await q('INSERT INTO comments(id,user_id,post_id,text) VALUES($1,$2,$3,$4)',[id,u.id,p.id,t]);if(p.user_id!==u.id)await addNotification(p.user_id,'comment',u.id,`@${u.username} commented on your post`,p.id);return json(res,201,{id,text:t});}
   if(req.url==='/api/search'&&req.method==='GET'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const term=clean(new URL(req.url,'http://x').searchParams.get('q')||'',80).replace(/^@/,'');if(!term)return json(res,200,{users:[],posts:[]});const users=await q(`SELECT u.*,COALESCE((SELECT count(*) FROM follows WHERE following_id=u.id),0)::int followers FROM users u WHERE lower(u.username) LIKE lower($1) OR lower(u.display_name) LIKE lower($1) ORDER BY u.username LIMIT 20`,[`%${term}%`]);const posts=await q(`SELECT p.id,p.caption,p.media_id,u.username,u.display_name FROM posts p JOIN users u ON u.id=p.user_id WHERE p.caption ILIKE $1 ORDER BY p.created_at DESC LIMIT 20`,[`%${term}%`]);return json(res,200,{users:users.rows.map(x=>publicUser(x,{followers:x.followers})),posts:posts.rows.map(x=>({...x,url:`/api/media/${x.media_id}`}))});}
   if(req.url==='/api/messages'&&req.method==='GET'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const other=new URL(req.url,'http://x').searchParams.get('with');if(other){const r=await q(`SELECT m.*,a.username sender_username,b.username recipient_username FROM messages m JOIN users a ON a.id=m.sender_id JOIN users b ON b.id=m.recipient_id WHERE (m.sender_id=$1 AND m.recipient_id=$2) OR (m.sender_id=$2 AND m.recipient_id=$1) ORDER BY m.created_at ASC LIMIT 200`,[u.id,other]);await q('UPDATE messages SET read_at=NOW() WHERE sender_id=$1 AND recipient_id=$2 AND read_at IS NULL',[other,u.id]);return json(res,200,{messages:r.rows});}const r=await q(`SELECT DISTINCT ON (peer) peer,username,display_name,last_text,last_at FROM (SELECT CASE WHEN sender_id=$1 THEN recipient_id ELSE sender_id END peer,CASE WHEN sender_id=$1 THEN r.username ELSE s.username END username,CASE WHEN sender_id=$1 THEN r.display_name ELSE s.display_name END display_name,m.text last_text,m.created_at last_at FROM messages m JOIN users s ON s.id=m.sender_id JOIN users r ON r.id=m.recipient_id WHERE m.sender_id=$1 OR m.recipient_id=$1 ORDER BY m.created_at DESC) x ORDER BY peer,last_at DESC`,[u.id]);return json(res,200,{conversations:r.rows});}
   if(req.url==='/api/messages'&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const b=await body(req),to=String(b.to||''),t=clean(b.text,2000);const r=await q('SELECT * FROM users WHERE id=$1 OR lower(username)=$1',[to.toLowerCase()]);const target=r.rows[0];if(!target||target.id===u.id)return json(res,400,{error:'Recipient not found'});if(!t)return json(res,400,{error:'Message is empty'});const id=crypto.randomUUID();await q('INSERT INTO messages(id,sender_id,recipient_id,text) VALUES($1,$2,$3,$4)',[id,u.id,target.id,t]);await addNotification(target.id,'message',u.id,`@${u.username} sent you a message`);return json(res,201,{message:{id,sender_id:u.id,recipient_id:target.id,text:t,created_at:new Date().toISOString()}});}
   if(req.url==='/api/notifications'&&req.method==='GET'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const r=await q(`SELECT n.*,u.username,u.display_name FROM notifications n LEFT JOIN users u ON u.id=n.actor_id WHERE n.user_id=$1 ORDER BY n.created_at DESC LIMIT 100`,[u.id]);return json(res,200,{notifications:r.rows});}
   if(req.url==='/api/notifications/read'&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});await q('UPDATE notifications SET read_at=NOW() WHERE user_id=$1',[u.id]);return json(res,200,{ok:true});}
   if(req.url==='/api/match/discover'&&req.method==='GET'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const wanted=oppositeGender(u.gender);const r=await q(`SELECT u.*,COALESCE((SELECT count(*) FROM follows WHERE following_id=u.id),0)::int followers FROM users u WHERE u.id<>$1 ${wanted?`AND u.gender=$2`:''} AND NOT EXISTS(SELECT 1 FROM match_actions a WHERE a.user_id=$1 AND a.target_id=u.id) ORDER BY u.created_at DESC LIMIT 30`,wanted?[u.id,wanted]:[u.id]);return json(res,200,{users:r.rows.map(x=>publicUser(x,{followers:x.followers}))});}
   if(req.url==='/api/match/action'&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const b=await body(req),target=String(b.targetId||''),action=b.action==='like'?'like':'pass';const t=(await q('SELECT * FROM users WHERE id=$1',[target])).rows[0];if(!t||t.id===u.id)return json(res,400,{error:'Invalid profile'});await q(`INSERT INTO match_actions(user_id,target_id,action) VALUES($1,$2,$3) ON CONFLICT(user_id,target_id) DO UPDATE SET action=EXCLUDED.action`,[u.id,t.id,action]);let matched=false;if(action==='like'){const reciprocal=await q(`SELECT 1 FROM match_actions WHERE user_id=$1 AND target_id=$2 AND action='like'`,[t.id,u.id]);if(reciprocal.rows[0]){const a=u.id<t.id?u.id:t.id,bid=u.id<t.id?t.id:u.id;await q('INSERT INTO matches(id,user_a,user_b) VALUES($1,$2,$3) ON CONFLICT(user_a,user_b) DO NOTHING',[crypto.randomUUID(),a,bid]);matched=true;await addNotification(t.id,'match',u.id,`You matched with @${u.username}`);await addNotification(u.id,'match',t.id,`You matched with @${t.username}`);}}return json(res,200,{matched,action});}
   if(req.url==='/api/matches'&&req.method==='GET'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const r=await q(`SELECT m.*,CASE WHEN m.user_a=$1 THEN b.id ELSE a.id END peer_id,CASE WHEN m.user_a=$1 THEN b.username ELSE a.username END peer_username,CASE WHEN m.user_a=$1 THEN b.display_name ELSE a.display_name END peer_name FROM matches m JOIN users a ON a.id=m.user_a JOIN users b ON b.id=m.user_b WHERE m.user_a=$1 OR m.user_b=$1 ORDER BY m.created_at DESC`,[u.id]);return json(res,200,{matches:r.rows});}
   if(req.url==='/api/game/invite'&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const b=await body(req),to=String(b.to||''),game=clean(b.game||'Trivia',50);const target=(await q('SELECT * FROM users WHERE id=$1 OR lower(username)=$1',[to.toLowerCase()])).rows[0];if(!target||target.id===u.id)return json(res,400,{error:'Player not found'});const id=crypto.randomUUID();await q('INSERT INTO game_invites(id,from_id,to_id,game) VALUES($1,$2,$3,$4)',[id,u.id,target.id,game]);await addNotification(target.id,'game',u.id,`@${u.username} invited you to play ${game}`);return json(res,201,{id,status:'pending'});}
   if(req.url==='/api/game/invites'&&req.method==='GET'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const r=await q(`SELECT i.*,u.username,u.display_name FROM game_invites i JOIN users u ON u.id=i.from_id WHERE i.to_id=$1 AND i.status='pending' ORDER BY i.created_at DESC`,[u.id]);return json(res,200,{invites:r.rows});}
   if(req.url.startsWith('/api/game/invite/')&&req.method==='POST'){const u=await auth(req);if(!u)return json(res,401,{error:'Login required'});const id=req.url.split('/').pop(),b=await body(req),status=['accepted','declined'].includes(b.status)?b.status:null;if(!status)return json(res,400,{error:'Invalid status'});const r=await q('UPDATE game_invites SET status=$1 WHERE id=$2 AND to_id=$3 RETURNING *',[status,id,u.id]);if(!r.rows[0])return json(res,404,{error:'Invite not found'});return json(res,200,{ok:true,status});}
   if(req.url==='/api/ai/support'&&req.method==='POST'){const b=await body(req),m=String(b.message||'').toLowerCase();let answer='Tell me what happened and what you expected Blizz to do.';if(m.includes('session')||m.includes('login'))answer='Your session issue is handled by the server session table. Log in again; Blizz no longer depends on a local-only session for the account.';if(m.includes('profile'))answer='Profile saves require an active server session. The profile endpoint now checks the session before saving.';if(m.includes('camera'))answer='Camera access uses the real browser device permission. Allow camera and microphone when prompted; Blizz remembers the browser permission state.';return json(res,200,{ok:true,diagnosis:{answer}});}
   if(req.method==='GET'&&!req.url.startsWith('/api/'))return staticFile(req,res);
   return json(res,404,{error:'Not found'});
  }catch(e){console.error(e);return json(res,500,{error:'Server error',detail:process.env.NODE_ENV==='production'?undefined:e.message});}
 });
 server.listen(PORT,'0.0.0.0',()=>console.log(`Blizz listening on port ${PORT}`));
}
main().catch(e=>{console.error('Blizz startup failed:',e);process.exit(1);});
